### ISSUE TITLE
crash oneplus one cm11 44s no gogle account xposed moudle

### ISSUE THREAD

**Issue by y7575355** [quarck/CalendarNotification#1]
java.lang.RuntimeException: Unable to start receiver com.github.quarck.calnotify.broadcastreceivers.BroadcastReceiverEventReminder: java.lang.IllegalStateException: desc must not be null
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2452)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at android.app.ActivityThread.handleReceiver(Native Method)
    at android.app.ActivityThread.access$1700(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5146)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: desc must not be null
    at com.github.quarck.calnotify.calendar.CalendarUtils.cursorToEventRecord(CalendarUtils.kt:60)
    at com.github.quarck.calnotify.calendar.CalendarUtils.getFiredEventsDetails(CalendarUtils.kt:97)
    at com.github.quarck.calnotify.broadcastreceivers.BroadcastReceiverEventReminder.onReceive(BroadcastReceiverEventReminder.kt:50)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2445)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at android.app.ActivityThread.handleReceiver(Native Method)
    at android.app.ActivityThread.access$1700(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5146)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by quarck** [comment]
Thanks for your report. It is probably related to Xposed framework -- I'll investigate how to fix it.

**Comment by quarck** [comment]
This particular issue should be fixed now. 
Calendar Notification Plus was attempting to read event description and probably Xposed was not allowing doing that. It turns out that I never used "description" anywhere in the UI, so I simply removed that field and any attempts to read it from system calendar. 

However I don't have device with xposed installed handy to test for any other possible issues, so please let me know if you face other issues. 

The fix is available since version 1.0.3. Please get binary from the "releases" folder on this repository (https://github.com/quarck/CalendarNotification/tree/master/releases). I'm not pushing it into F-Droid or Google Play at the moment since I'm not sure that all the bugs are fixed. 

Please note that guys from F-Droid have built this project themselves and signed with their own keys, so I you try upgrading directly to the new version - it might fail. You need to re-install it completely if you have it currently installed. 

Thanks, 
Sergey

**Comment by y7575355** [comment]
Thank you
Can you explain how can I download the apk?

**Comment by quarck** [comment]
You can click on "View raw" here: https://github.com/quarck/CalendarNotification/blob/master/releases/1.0.3/CalendarNotificationPlus_1.0.3.apk

Alternatively you could download it from my dropbox: 

https://dl.dropboxusercontent.com/u/25074445/cnotify/CalendarNotificationPlus_1.0.3.apk

**Comment by y7575355** [comment]
works 
Thank you
Can you ask fdroid to update theirs?

**Comment by quarck** [comment]
I've submitted it into the submission queue (here: https://f-droid.org/forums/topic/calendar-notifications-plus-update-to-version-1-0-3/), but it could take a while for them to actually update it.
