### ISSUE TITLE
after snooze edited the event when saved the event the app crashed

### ISSUE THREAD

**Issue by y7575355** [quarck/CalendarNotification#2]
java.lang.RuntimeException: Unable to start receiver com.github.quarck.calnotify.broadcastreceivers.BroadcastReceiverCalendarChanged: java.lang.IllegalStateException: location must not be null
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2452)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:595)
    at android.app.ActivityThread.handleReceiver(Native Method)
    at android.app.ActivityThread.access$1700(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5146)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: location must not be null
    at com.github.quarck.calnotify.calendar.CalendarUtils.cursorToEventRecord(CalendarUtils.kt:58)
    at com.github.quarck.calnotify.calendar.CalendarUtils.getEvent(CalendarUtils.kt:153)
    at com.github.quarck.calnotify.EventsManager$Companion.reloadCalendar(EventsManager.kt:89)
    at com.github.quarck.calnotify.EventsManager$Companion.onCalendarChanged(EventsManager.kt:154)
    at com.github.quarck.calnotify.broadcastreceivers.BroadcastReceiverCalendarChanged.onReceive(BroadcastReceiverCalendarChanged.kt:32)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:2445)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:595)
    at android.app.ActivityThread.handleReceiver(Native Method)
    at android.app.ActivityThread.access$1700(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5146)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by quarck** [comment]
Thank you, I'd take a look.

**Comment by quarck** [comment]
Please try this version: 
https://dl.dropboxusercontent.com/u/25074445/cnotify/CalendarNotificationPlus_1.0.4.apk

**Comment by quarck** [comment]
I believe this should be fixed. Please let me know if you are still seeing this issue. Version with the fix would be on F-Droid in a few days. Right now latest version could be found on my Dropbox: 

https://dl.dropboxusercontent.com/u/25074445/cnotify/CalendarNotificationPlus_1.0.6.apk

Or on Google Play (would be available in a few hours).
