### ISSUE TITLE
java.lang.RuntimeException: Unable to start receiver com.github.quarck.calnotify.broadcastreceivers.BroadcastReceiverReminderAlarm: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)

### ISSUE THREAD

**Issue by quarck** [quarck/CalendarNotification#25]
java.lang.RuntimeException: Unable to start receiver com.github.quarck.calnotify.broadcastreceivers.BroadcastReceiverReminderAlarm: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2955)
	at android.app.ActivityThread.access$1800(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1015)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:136)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
	at com.github.quarck.calnotify.eventsstorage.EventsStorage.getEventsImpl(EventsStorage.kt:271)
	at com.github.quarck.calnotify.eventsstorage.EventsStorage.getEvents(EventsStorage.kt:384)
	at com.github.quarck.calnotify.EventsManager.hasActiveEvents(EventsManager.kt:95)
	at com.github.quarck.calnotify.broadcastreceivers.BroadcastReceiverReminderAlarm$onReceive$1.invoke(BroadcastReceiverReminderAlarm.kt:53)
	at com.github.quarck.calnotify.broadcastreceivers.BroadcastReceiverReminderAlarm$onReceive$1.invoke(BroadcastReceiverReminderAlarm.kt:39)
	at com.github.quarck.calnotify.utils.SystemUtilsKt.wakeLocked(SystemUtils.kt:49)
	at com.github.quarck.calnotify.broadcastreceivers.BroadcastReceiverReminderAlarm.onReceive(BroadcastReceiverReminderAlarm.kt:49)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2948)
	... 9 more

**Comment by quarck** [comment]
Most likely it is a threading issue: SQLite is not allowing DB to be opened from multiple threads or processes at the same time. In this case Snooze activity is launched in a separate task.

**Comment by quarck** [comment]
Should be fixed in 4786b1075432f82e65368719e9f53e59cd72c34b
