### ISSUE TITLE
Fatal Exception on android 6.0.1 (NoSuchMethodError: No virtual method setPeriodic)

### ISSUE THREAD

**Issue by bpoussin** [quarck/CalendarNotification#291]
Hey,

I just download and install version 4.0.8 from f-droid and application has exception.
4.0.8 normally work on android 6 (i see that in description on f-droid) 

```
09-22 14:11:07.346 14207 14207 E AndroidRuntime: FATAL EXCEPTION: main
09-22 14:11:07.346 14207 14207 E AndroidRuntime: Process: com.github.quarck.calnotify, PID: 14207
09-22 14:11:07.346 14207 14207 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setPeriodic(JJ)Landroid/app/job/JobInfo$Builder; in class Landroid/app/job/JobInfo$Builder; or its super classes (declaration of 'android.app.job.JobInfo$Builder' appears in /system/framework/framework.jar)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at com.github.quarck.calnotify.calendarmonitor.CalendarMonitorPeriodicJobService$Companion.getJobInfo(CalendarMonitorService.kt:271)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at com.github.quarck.calnotify.calendarmonitor.CalendarMonitorPeriodicJobService$Companion.schedule(CalendarMonitorService.kt:285)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at com.github.quarck.calnotify.app.ApplicationController.onMainActivityStarted(ApplicationController.kt:775)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at com.github.quarck.calnotify.ui.MainActivity.onStart(MainActivity.kt:164)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6373)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:150)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5444)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:727)
09-22 14:11:07.346 14207 14207 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
09-22 14:11:07.348  1766  2971 W ActivityManager:   Force finishing activity com.github.quarck.calnotify/.ui.MainActivity

```

**Comment by quarck** [comment]
Thanks. I haven't thought about Job Scheduler changes in Android 7 - so android 6 has no such API yet. Will make a change to use old-style services for Android 6

**Comment by quarck** [comment]
Actually JobScheduler is present on Android N 6.0.1. The only problem was particular method override for "setPeriodic".
